language: go
go:
  - 1.7.1
env:
  global:
    - SSH_KEY="GIT_TOKEN"
    - GIT_NAME="Gtk Theming Guide"
    - GIT_EMAIL="cruelplatypus67@gmail.com"
    - SOURCE_DIR="public"
    - DEPLOY_BRANCH="code"
    - TEMP_DIR=$(sudo mktemp -d /tmp/$REPO_NAME.XXXX)
secure: "pxaTi0trZvNgdKI5LJRIRNKwke3Aqb+IBBltHQx9DG4dJueci+l+BtgvEWZGI5Ct75JuGqDha+Cj/XqdHOAPbvPE298GKawbR1V4Jg5WlWemThCm1Mq0Z7nkBVreo+T+EMNPKNy5Zu3nu9BT8FxEBnORZWdqtadx9l833ZuhvZa1hT8H5iZl5PSGJ3UKNgw/E8oJPKK3NitLh2PgWLA0DNytgKMQPvi7VbgKzBORpFuPvblITXOaKiPF0yQ0sGVHcGSv/TgnWkmLQC5yof/WGzqO4O3E/5pWw/CCEXJvTgpXWipcXi5tcr9oFvLJL20xdRCLJHWDe7E5qaDNqjrpMXda6xCfft7KbUXYbq3Ikb8YVVgqHnyvWxMM1QELHuPZErX1mPwOTPgW2qFidCm+IsPubZ9y1k6JiuZE5azRGBLUETs7S2VDDc6GCjC0/WpURe+fdCz7ZeyS2cc3JPOIZlUjhnZlhS4VPVTjIp7D0ro+pI7kT8vBk5o2FM2F6v9D6R+R7NAp6lVeRzgndLS/LuuEZc9YlxYSJy8hjzVJKrFxIJP/sqyy8lB5ZNurjA5hf4NUuddwabGClqyl1L8dixeNEj8bxakRocpXkEsDjvFpWFfyFm7Uo0g6RSt2hRdMykPBt5rlgB+UU1fXnJ7aV0DTWup8pS7/uO1j4s7gmC0="
before_script:
  - git clone --branch v2 https://github.com/go-yaml/yaml $GOPATH/src/gopkg.in/yaml.v2
  - go get -u -v github.com/spf13/hugo
script:
  - git submodule init
  - hugo
after_success:
  - chmod a+x ./scripts/deploy.sh
  - ./scripts/deploy.sh
