baseurl = "http://gtkthemingguide.ml"
#relativeurls = false
languageCode = "en-us"
publishDir = "docs"
title = "Gtk Theming Guide"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
#Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "surajmandalcell"
	description = "Documentation for people wanting to create their own gtk theme"
	copyright = "Released under the MIT license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/surajmandalcell/Gtk-Theming-Guide"

	version = "1.0.0"
	# logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "brown"
    	accent  = "blue-grey"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = "surajmandalcell"
	github  = "surajmandalcell"
	email   = "cruelplatypus67@gmail.com"


[[menu.main]]
	name   = "Introduction"
	url    = "/"
	weight = 0

[[menu.main]]
	name   = "Getting started"
	url    = "getting-started/"
	weight = 10

[[menu.main]]
	name   = "Creating GTK3 Themes"
	url    = "creating-gtk3-themes/"
	weight = 20

[[menu.main]]
 	name   = "Creating Icon Theme"
 	url    = "creating-icon-theme/"
 	weight = 30

[[menu.main]]
	name   = "License"
	url    = "license/"
	weight = 40

# [[menu.main]]
# 	name   = "About"
# 	url    = "about/"
# 	weight = 60

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
